In [2]:
#without numpy
import time

sum=0
start_time=time.time()

for num in range(10000000):
    sum=sum+num
print("sum= ",sum)

end_time=time.time()

python_time=end_time-start_time

print("Time taken= ",python_time)


sum=  49999995000000
Time taken=  1.9899988174438477


In [3]:
#with numpy 
import time
import numpy as np

sum=0

start_time=time.time()

numbers=np.arange(10000000)

sum=np.sum(numbers, dtype=np.uint64)

print("sum= ",sum)

end_time=time.time()

python_time=end_time-start_time

print("Time taken= ",python_time)


sum=  49999995000000
Time taken=  0.11487078666687012


# numpy array

In [2]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9])   # one dimentional numpy array 
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b=np.array([[1,2,3,4,5,6,7,8,9],[1,12,13,15,16,7,55,89,10]])   # two dimentional numpy array/matrix 
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1, 12, 13, 15, 16,  7, 55, 89, 10]])

In [8]:
number =[1,2,3,4,5,6,7,8]
c= np.array(number)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
a1= [1,2,3,4,5]
a2=[11,12,13,14,15]
b=np.array([a1,a2])
b


array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [11]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Reshape

In [12]:
b.shape

(2, 5)

In [13]:
n=np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
x.shape  #****************************

(12,)

In [18]:
x.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
x.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
x.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [21]:
x.reshape(1,12)   #********************

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [23]:
    numbers_1 = [1,2,3]
    numbers_2 = [4,5,6]
    numbers_3 = [7,8,9]
    a = np.array([numbers_1 + numbers_2 + numbers_3])
    a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
    numbers_1 = [1]
    numbers_2 = [4]
    numbers_3 = [7]
    a = np.array([numbers_1, numbers_2, numbers_3])
    a

array([[1],
       [4],
       [7]])

In [27]:
    numbers = np.arange(1,13) 
    numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
numbers.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
    numbers = np.arange(1,13) 
    numbers.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [34]:
    d=np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

In [35]:
d.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
    a = np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
     
    a.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

# Element wise operation

In [39]:
a=[1,2,3]
b=[4,5,6]
c=a+b
c

[1, 2, 3, 4, 5, 6]

In [40]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
c

array([5, 7, 9])

In [41]:
a=np.array([1,2,3])*3
a

array([3, 6, 9])

In [43]:
b=np.array([1,2,3])

c=b+[4]
c

array([5, 6, 7])

In [45]:
d=np.array([4,5])
e=b+d
e

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

# Aggregate operations

In [49]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.sum(a,axis=1)

array([ 6, 15])

In [51]:
np.sum(a,axis=0)

array([5, 7, 9])

In [52]:
np.mean(a,axis=1)

array([2., 5.])

In [53]:
np.min(a,axis=1)

array([1, 4])

In [54]:
np.max(a,axis=1)

array([3, 6])

# Indexing

In [56]:
a[1]

array([4, 5, 6])

In [57]:
a[1,1]

5

In [58]:
a[0,-2] 

2

In [59]:
a[0,1]

2

# Array slicing


In [60]:
b=np.array([1,2,3,4,5,6])
b[2:4]

array([3, 4])

In [61]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [64]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [65]:
a[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
a[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

# Append row and column

In [2]:
import numpy as np 

ar=np.arange(1,21)
ar=ar.reshape(4,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [3]:
extra=np.array([21,22,23,24,25])

In [6]:
np.append(ar,[extra],axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
np.append(ar,[extra],axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 1

In [11]:
extra1=np.array([21,22,23,24])
j=extra1.reshape(4,1)
j

array([[21],
       [22],
       [23],
       [24]])

In [12]:
np.append(ar,j,axis=1)

array([[ 1,  2,  3,  4,  5, 21],
       [ 6,  7,  8,  9, 10, 22],
       [11, 12, 13, 14, 15, 23],
       [16, 17, 18, 19, 20, 24]])

# Insert row and column

In [3]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
b=np.array([21,23,22,24])
b

array([21, 23, 22, 24])

In [5]:
np.insert(a,2,b,axis=0)  #insert(a, row number , b, axis =)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [21, 23, 22, 24],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
np.insert(a,2,b,axis=1)

array([[ 1,  2, 21,  3,  4],
       [ 5,  6, 23,  7,  8],
       [ 9, 10, 22, 11, 12],
       [13, 14, 24, 15, 16]])

# Array Delete

In [7]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
np.delete(a,2,axis=1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12],
       [13, 14, 16]])

In [9]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
np.delete(a,2,axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16]])


# Append ->  .append(a,b,axis)
# Insert ->  .insert(a,n,a,axis)
# delete-> .delete(a,n,axis) 
a- source array ,  b=inserted array / delete , n=index  
for append and insert -> inserted array should be in right dimension || reshape